"""Norway — Brønnøysundregistrene / Enhetsregisteret.

**Stub. T02 (rules) and T03 (client + mapping) fill this in.**

The class below fixes the metadata and the shape; every method raises
``RegistryError(code="not_implemented")`` until the implementers land. Do not
change the class name, the ``country``/``registry`` values, or the method
signatures without an entry in ``DECISIONS.md`` — ``api/`` and ``mcp/`` build
against them.

Files T02/T03 add next to this one, per ``NORBIZ_SPEC.md``:
    rules.py    -- MOD11, org-form table, status derivation, deadlines (T02)
    client.py   -- httpx client for data.brreg.no, 5s timeout, one retry (T03)
    mapping.py  -- Enhetsregisteret JSON -> CompanyReport (T03)
    cache.py    -- SQLite cache, 24h TTL (T03)
"""

from __future__ import annotations

from datetime import date
from typing import ClassVar

from registry_mcp.core.models import (
    CompanyReport,
    Deadline,
    ErrorCode,
    RegistryError,
    SearchResult,
)
from registry_mcp.core.registry import Registry, register

__all__ = ["BrregRegistry"]


class BrregRegistry(Registry):
    """The Norwegian Central Coordinating Register for Legal Entities."""

    country: ClassVar[str] = "NO"
    registry: ClassVar[str] = "brreg"
    name: ClassVar[str] = "Enhetsregisteret (Brønnøysundregistrene)"
    id_scheme: ClassVar[str] = "organisasjonsnummer"
    id_example: ClassVar[str] = "923609016"
    id_description: ClassVar[str] = (
        "A Norwegian organisasjonsnummer (orgnr): nine digits, the ninth a MOD11 "
        "check digit. Written '923 609 016' or '923609016'; a VAT number adds 'MVA'."
    )
    source_url: ClassVar[str] = "https://data.brreg.no/enhetsregisteret/api"
    license: ClassVar[str] = "NLOD 2.0"
    is_stub: ClassVar[bool] = False

    def _todo(self, what: str) -> RegistryError:
        return RegistryError(
            ErrorCode.NOT_IMPLEMENTED,
            f"{what} is not implemented yet for country NO.",
            hint=(
                "The Norwegian module is still being built. Retry after the next release, "
                "or use list_countries to see what is available now."
            ),
            country=self.country,
            registry=self.registry,
        )

    def validate_id(self, id: str) -> str:
        """Normalise and MOD11-check an organisasjonsnummer. Implemented by T02."""
        raise self._todo("validate_id")

    async def lookup(self, id: str) -> CompanyReport:
        """Fetch one entity from Enhetsregisteret. Implemented by T03."""
        raise self._todo("lookup")

    async def search(self, name: str, limit: int = 10) -> SearchResult:
        """Search Enhetsregisteret by name. Implemented by T03."""
        raise self._todo("search")

    def deadlines(self, report: CompanyReport, today: date) -> list[Deadline]:
        """Norwegian filing deadlines for this entity. Implemented by T02."""
        raise self._todo("deadlines")

    def rules_markdown(self) -> str:
        """Served as the MCP resource ``registry://rules/NO``. Filled in by T02."""
        return (
            "# Norway — Brønnøysundregistrene\n\n"
            "Rules documentation is generated by `registries/no/rules.py` (T02). "
            "See `NORBIZ_SPEC.md` for the authoritative version."
        )


register(BrregRegistry())
