"""Norway — Brønnøysundregistrene / Enhetsregisteret.

``validate_id`` and ``deadlines`` delegate to ``registries/no/rules.py`` (T02,
MOD11 / org-form table / status derivation / the six deadlines). ``lookup``
and ``search`` delegate to ``registries/no/client.py`` (T03, HTTP + cache +
``registries/no/mapping.py``).

Every delegate is imported lazily, inside the method body, rather than at
module top level. T02's ``rules.py`` and T03's ``client.py`` are built in
parallel by different agents in this session; importing either eagerly here
would make *this* module — which ``registries/__init__.py`` imports
unconditionally at package load — fail to import whenever the other task's
file is momentarily absent or mid-edit. A lazy import only pays that risk at
call time, for the one method that actually needs it.
"""

from __future__ import annotations

from datetime import date
from typing import ClassVar

from registry_mcp.core.models import CompanyReport, Deadline, SearchResult
from registry_mcp.core.registry import Registry, register

__all__ = ["BrregRegistry"]


class BrregRegistry(Registry):
    """The Norwegian Central Coordinating Register for Legal Entities."""

    country: ClassVar[str] = "NO"
    registry: ClassVar[str] = "brreg"
    name: ClassVar[str] = "Enhetsregisteret (Brønnøysundregistrene)"
    id_scheme: ClassVar[str] = "organisasjonsnummer"
    id_example: ClassVar[str] = "923609016"
    id_description: ClassVar[str] = (
        "A Norwegian organisasjonsnummer (orgnr): nine digits, the ninth a MOD11 "
        "check digit. Written '923 609 016' or '923609016'; a VAT number adds 'MVA'."
    )
    source_url: ClassVar[str] = "https://data.brreg.no/enhetsregisteret/api"
    license: ClassVar[str] = "NLOD 2.0"
    is_stub: ClassVar[bool] = False

    def validate_id(self, id: str) -> str:
        """Normalise and MOD11-check an organisasjonsnummer (``registries/no/rules.py``, T02)."""
        from registry_mcp.registries.no import rules

        result: str = rules.validate_orgnr(id)
        return result

    async def lookup(self, id: str) -> CompanyReport:
        """Fetch one entity from Enhetsregisteret (``registries/no/client.py``, T03)."""
        from registry_mcp.registries.no import client

        return await client.lookup(id)

    async def search(self, name: str, limit: int = 10) -> SearchResult:
        """Search Enhetsregisteret by name (``registries/no/client.py``, T03)."""
        from registry_mcp.registries.no import client

        return await client.search(name, limit)

    def deadlines(self, report: CompanyReport, today: date) -> list[Deadline]:
        """Norwegian filing deadlines for this entity (``registries/no/rules.py``, T02)."""
        from registry_mcp.registries.no import rules

        result: list[Deadline] = rules.deadlines(report, today)
        return result

    def format_id(self, id: str) -> str:
        """``"923609016"`` -> ``"923 609 016"`` (``registries/no/mapping.py``, T03)."""
        from registry_mcp.registries.no import mapping

        result: str = mapping.format_orgnr(id)
        return result

    def rules_markdown(self) -> str:
        """Served as the MCP resource ``registry://rules/NO``. Filled in by T02."""
        try:
            from registry_mcp.registries.no import rules

            markdown: str = rules.rules_markdown()
            return markdown
        except (ImportError, AttributeError):
            return (
                "# Norway — Brønnøysundregistrene\n\n"
                "Rules documentation is generated by `registries/no/rules.py` (T02), "
                "not yet available. See `NORBIZ_SPEC.md` for the authoritative version."
            )


register(BrregRegistry())
